spring:
  application:
    name: dsmsystem

  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://db.riecriotklkopqpqfcvh.supabase.co:5432/postgres
    url: jdbc:postgresql://metro.proxy.rlwy.net:47029/railway
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect